name: Dynamic Template

on:
  create:
  workflow_dispatch:

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@dev

      - name: "💾  Github Repository Metadata"
        uses: varunsridharan/action-repository-meta@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "💫  Dynamic Template Render"
        uses: varunsridharan/action-dynamic-readme@dev
        with:
          GLOBAL_TEMPLATE_REPOSITORY: $GITHUB_REPOSITORY
          files: |
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}