name: Production Environment CI/CD

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  lint_prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run lint

  deploy_prod:
    runs-on: ubuntu-latest
    needs: lint_prod

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: ⌨️ Use Vercell CLI
      run: npm install --global vercel@canary

    - name: 🖥️ Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

    - name: 🔨 Build Project Artifacts
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

    - name: 📂 Sync Files
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
