name: Production Environment CI/CD

on:
  push:
    branches:
      - gh-pages

jobs:
  lint_prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run lint

  deploy_prod:
    runs-on: ubuntu-latest
    needs: lint_prod

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: 🔨 Build Project
      run: |
        npm ci
        npm run build:prod

    - name: 📂 Sync files
      uses: actions/deploy-pages@v4
